#ifndef CONSTANTES_H_INCLUDED
#define CONSTANTES_H_INCLUDED

#define TODO_OK 0
#define ARCHIVO_NO_ENCONTRADO 10
#define CARPETA_NO_ENCONTRADA 15
#define NO_SE_PUEDE_CREAR_ARCHIVO 20
#define NO_ES_24BITS 24
#define CONCATENADO 1
#define FALTAN_INSTRUCCIONES 30
#define INSTRUCCION_INVALIDA 40
#define HIJOS_NO_CREADOS 50
#define ERROR_PIPE 60
#define ERROR_SEM 61
#define ERROR_MEM_COMP 62

#define CLAVE_MEMORIA 1234
#define CANTIDAD_COLORES 3
#define CANTIDAD_HIJOS 4
#define HIJO_CREADO 80
#define MAX_BUFFER 512
#endif // CONSTANTES_H_INCLUDED
